### ISSUE TITLE
Adding internal url options to contact previews

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#111]
In asking for PRA contact information from agencies, some provide references to internal sites only accessible to their agency's employees. Since we know a common scenario is "who at my agency should I talk to", these links could be valuable to share.

We should consider:
* where they should appear in the preview
* how they should be distinguished as internal
* is "internal" the right word?

**Comment by cmajel** [comment]
A few thoughts after talking with @hursey013:
* we now have multiple agencies who have internal links in addition to external urls.
* it feels fair to offer 1 internal and 1 external link for each office
* we could do this by creating distinguished `internal` and `external` fields in the json

Still a question over how to show / explain that a url is internal

**Comment by cmajel** [comment]
Adding a few options for @amandacostello's review. We're trying to determine what's the right way to label a link to an internal / intranet resource on PRA.

Here are two options - open to suggestions

<img width="540" alt="Screen Shot 2019-05-08 at 10 18 47 AM" src="https://user-images.githubusercontent.com/2374206/57382637-4d1a5c00-717b-11e9-91eb-ce2de958e7d6.png">
<img width="590" alt="Screen Shot 2019-05-08 at 10 22 00 AM" src="https://user-images.githubusercontent.com/2374206/57382639-4d1a5c00-717b-11e9-8346-57aedd20ee20.png">

**Comment by hursey013** [comment]
Done!
