### ISSUE TITLE
Do users know who's authored the content?

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#113]
A core need of users is for clear, authoritative guidance that feels based on PRA realities. A user visiting the site should be able to determine that OIRA is the author of this content and that it is based on official guidance, and therefore can be trusted.

Do users identify OIRA as the site author?

**Comment by amandacostello** [comment]
Going to be clearing up the Footer language for this.

**Comment by amandacostello** [comment]
Re-wrote footer language for more clarity.
