### ISSUE TITLE
Rename this Repo

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-pra#141]
Now that the site will no longer be called `pra.gov`, can we change the name to `digitalgov-pra`? I worry that it will cause confusion down the road when IT people are looking at the repo and trying to figure out why it doesn't map to that domain.

**Comment by hursey013** [comment]
@ecayer @amandacostello any objections to me just going ahead and renaming it now?

**Comment by ecayer** [comment]
No objections. I had expected it to be `pra-guide`, but more than happy to meet digital.gov naming conventions!

**Comment by hursey013** [comment]
Done!
