### ISSUE TITLE
New Header, New Name

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov-pra#143]
We need to apply the Digital.gov banner to the top of the PRA guide.

**Digital.gov Guide logo:** [digitalgov-guide-logo.svg.zip](https://github.com/GSA/pra.gov/files/3139231/digitalgov-guide-logo.svg.zip)
**Hex:** `#2E2C40` or `indigo-warm-80`

The Digital.gov Guide logo and "explore" link should link to https://digital.gov/resources

---

![image](https://user-images.githubusercontent.com/395641/57094286-31780700-6cde-11e9-839c-700302c8ce49.png)

**Comment by cmajel** [comment]
per convo with @jeremyzilar this afternoon, we're going to move forward with Option B.

@hursey013 I've updated the figma file with the new headers and adding here:

**logo files**
[guide-to-pra--logos.zip](https://github.com/GSA/digitalgov-pra/files/3159289/guide-to-pra--logos.zip)

**logo notes sheet**
![Logo-notes](https://user-images.githubusercontent.com/2374206/57408644-2debf080-71b4-11e9-9c8e-37d9aa4d4635.jpg)

**header styles**
![Headers](https://user-images.githubusercontent.com/2374206/57408707-5e338f00-71b4-11e9-9d1b-35bafec22b66.jpg)

A note on header styles
* After a convo with the USWDS channel, I think we should keep the "here's how you know" dropdown on the "Official gov site" banner.
* We should recolor this dropdown to avoid clashing with the digital.gov banner 
* I adjusted the width of the mobile menu/close button slightly to accommodate the wider logo

This is ready for implementation
