### ISSUE TITLE
Check font-weight on headings

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#152]
I have a suspicion that Merriweather's `bold` weight on the site is actually pointing to `Merriweather Heavy` instead of `Merriweather bold`.

Here is what I see in the Figma styleguide vs what I see on the site:
![Frame 2](https://user-images.githubusercontent.com/2374206/57239387-beca9c80-6ff9-11e9-8dfc-4c7363ba66ed.jpg)

**Comment by cmajel** [comment]
@hursey013 could you confirm what the font-weight mapping is and if we're hitting the right weight?

**Comment by hursey013** [comment]
The weights are configured as:
```
$theme-font-weight-thin: false;
$theme-font-weight-light: 300;
$theme-font-weight-normal: 400;
$theme-font-weight-medium: false;
$theme-font-weight-semibold: 600;
$theme-font-weight-bold: 700;
$theme-font-weight-heavy: false;
```

I believe the headings are mapped to `$theme-font-weight-bold`. `$theme-font-weight-semibold` was disabled by default, but I enabled it to use it in a few places (like the mobile `MENU` link). I suspect we may want to try out setting `$theme-font-weight-bold` to `600`?

**Comment by cmajel** [comment]
Yea I am still learning how USWDS links up its variables with its fonts. I wonder if we are running into `bold` being mapped to `semibold` and having a case of general variables not matching specifics. I would have thought though that Merriweather bold would be a `700` value and Heavy would be `900`.

**Comment by hursey013** [comment]
I went ahead and made h1-h3 normal font weight, left h4-h6 bold. Let me know what you think: https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/

**Comment by cmajel** [comment]
@hursey013 I like this much better. Still a little confounded by why it happened, but I'll take it. Closing this out.
