### ISSUE TITLE
Improve Authorship Understanding

### ISSUE THREAD

**Issue by qhirschomb** [GSA/digitalgov-pra#153]
Move the statement that the site is maintained by OIRA down to within the footer near Digital.gov
![Uploading Screenshot of authority content move.png…]()

Folks took a long time to think about who owns and operates the site. They often went to the bottom of the page and the seal attracted their attention - answer was often not sure, EOP or digital.gov - they missed the language above that. If it was on the footer instead, it would also be on every page rather than just the home page

**Comment by cmajel** [comment]
@qhirschomb we have a pending PR that has some updated language from @amandacostello - does this resolve this issue?

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/amandacostello-patch-3/

Note that this link shows only language changes, and the updated footer styles are on a different branch.

**Comment by qhirschomb** [comment]
@cmajel we typically use the term 'within' rather than 'part of' the Office of Management and Budget. 
Flagging for @mmcmanusOMB as verification
