### ISSUE TITLE
Update authorship statement to indicate OIRA is within OMB

### ISSUE THREAD

**Issue by qhirschomb** [GSA/digitalgov-pra#154]
Could we update the language on the bottom from:

PRA.gov’s content is maintained by The Office of Information and Regulatory Affairs (OIRA) and PRA officers across federal government. This site is a product of 10x and is supported by Digital.gov.

to

PRA.gov’s content is maintained by The Office of Information and Regulatory Affairs (OIRA) within the Office of Management and Budget and PRA officers across federal government. This site is a product of 10x and is supported by Digital.gov.

As a sidebar question - could there be clarifying language around 10x? That was a term unfamiliar to most users

**Comment by hursey013** [comment]
@amandacostello was this resolved with your latest footer changes?
