### ISSUE TITLE
Style top nav hover state

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#156]
From the 5/7 style sync

In our style guide, I created a differentiated style for hovering on a top nav item from an active nav item. Currently the site uses just the active style. 

In styleguide:
<img width="614" alt="Screen Shot 2019-05-07 at 3 01 51 PM" src="https://user-images.githubusercontent.com/2374206/57325866-1986f580-70d9-11e9-918d-8a7dd69bbb18.png">

**Comment by hursey013** [comment]
Done!
