### ISSUE TITLE
Even out spacing on side navs that have internal links

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#158]
from 5/7 styling sync.

On the sidenavs that have internal links, the last internal link has a little less spacing on the bottoms. Can we add a little space to the last internal link to keep it even? 

![image](https://user-images.githubusercontent.com/2374206/57326790-43411c00-70db-11e9-9aec-d8cacf4eaabd.png)

**Comment by hursey013** [comment]
Done!
