### ISSUE TITLE
Users didn't realize when an agency didn't exist on the contact page

### ISSUE THREAD

**Issue by qmanderson1** [GSA/digitalgov-pra#159]
Could we communicate to users when the agency they're searching for doesn't exist? Users continued searching for agencies not listed on the contact pages as opposed to realizing they just weren't there.

**Comment by cmajel** [comment]
Per convo with @qmanderson1, this could be accomplished by having a more explicit `no results found` message, which also relates to a convo I had with @hursey013 

What do you both think about updating the `no results` message to this?

```
We don't have a listing for this agency yet.

Often, the Office of the Chief Information Officer can point you in the right direction.
```

**Comment by cmajel** [comment]
awesome - @hursey013 passing to you to update the "no results" message.

**Comment by hursey013** [comment]
There are some limitations with the javascript library we are using, so it's no perfect, but added the updated text and hopefully this can be improved upon in the future.

Update: https://github.com/GSA/digitalgov-pra/commit/a45c62c32f706224d8df1148b115f990e797fd53

Preview link: https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/
