### ISSUE TITLE
Adjust font-weight of top nav items

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#161]
Currently the site uses `font-weight: 700;` for the top nav items:

*font-weight 700*
<img width="1036" alt="pra-700" src="https://user-images.githubusercontent.com/2374206/57327400-e0e91b00-70dc-11e9-8744-e7bc0b8798f5.png">

In the styleguide, we had it at `600` / `PublicSans Semibold`. Can we adjust it to that weight?

*font-weight 600*
<img width="1039" alt="pra-600" src="https://user-images.githubusercontent.com/2374206/57327408-e47ca200-70dc-11e9-8ef4-2aa526c8fb99.png">

**Comment by hursey013** [comment]
Update: https://github.com/GSA/digitalgov-pra/commit/39aad53391747548be267cbd46f9b6e27716c2d3

Preview: https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/

**Comment by cmajel** [comment]
Looks great! 👍 closing this.
