### ISSUE TITLE
Results for glossary terms in search

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#166]
from 5/7 styling sync

**Current**
The site search includes results for glossary terms that currently appear like this:

As results:
<img width="1116" alt="Screen Shot 2019-05-07 at 3 24 52 PM" src="https://user-images.githubusercontent.com/2374206/57327196-4dafe580-70dc-11e9-92b9-34d807945dbb.png">

Results page:
<img width="1148" alt="Screen Shot 2019-05-07 at 4 44 51 PM" src="https://user-images.githubusercontent.com/2374206/57331997-e26c1080-70e7-11e9-83ee-f19215b44d79.png">

It is not immediately clear that these results are related to the glossary and that you'll get a definition. 

**Proposed**
Two thoughts for consideration.

1. On results page, Add "glossary" to the page title and show in the results
<img width="735" alt="Screen Shot 2019-05-07 at 4 49 31 PM" src="https://user-images.githubusercontent.com/2374206/57332118-1fd09e00-70e8-11e9-8d87-38d6e0ddc997.png">

2. On individual result, add "glossary" to the title
<img width="1052" alt="Screen Shot 2019-05-07 at 4 53 02 PM" src="https://user-images.githubusercontent.com/2374206/57332464-cddc4800-70e8-11e9-99d6-f37a9bec3a1f.png">

3. On individual result, add a "glossary" subhead rather than a full title

<img width="1022" alt="Screen Shot 2019-05-07 at 4 47 33 PM" src="https://user-images.githubusercontent.com/2374206/57332445-c6b53a00-70e8-11e9-9d82-6b0cb2dff9d9.png">

pinging @amandacostello and @hursey013 for thoughts

**Comment by hursey013** [comment]
Update: https://github.com/GSA/digitalgov-pra/commit/bf1f3fabaa7691d62bc7194b06587296a4b253fb

Preview link: https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/

**Comment by cmajel** [comment]
Nice! looks good to me - @amandacostello any thoughts on language? Otherwise we can close this out.

**Comment by hursey013** [comment]
Closing this out!
