### ISSUE TITLE
Bookmark icons need further testing

### ISSUE THREAD

**Issue by qmanderson1** [GSA/digitalgov-pra#167]
In the last round of testing users didn't realize the bookmarks next to terms meant the term could be found in the glossary. We'd like to test this using bookmarks next more technical terms that users are more likely to desire definitions for. 

<img width="562" alt="Screen Shot 2019-05-07 at 3 03 31 PM" src="https://user-images.githubusercontent.com/23083747/57379965-f3636300-7175-11e9-8aaa-2bb727421b5a.png">

**Comment by cmajel** [comment]
additional conversation here #157
