### ISSUE TITLE
Update footer styling

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#168]
Per the comments in #153 and #155, I'm proposing this update to our footer styling:

**current**
<img width="1046" alt="Screen Shot 2019-05-08 at 11 49 53 AM" src="https://user-images.githubusercontent.com/2374206/57389448-3af2ea80-7188-11e9-8c86-13084c4ccd40.png">
<img width="397" alt="Screen Shot 2019-05-08 at 11 50 01 AM" src="https://user-images.githubusercontent.com/2374206/57389449-3b8b8100-7188-11e9-9818-901cff456db1.png">

**proposed**
![desktop](https://user-images.githubusercontent.com/2374206/57389627-958c4680-7188-11e9-9a93-c97f3e53f685.jpg)
![mobile](https://user-images.githubusercontent.com/2374206/57389628-958c4680-7188-11e9-8e9e-2d337c69af5c.jpg)

Changes include:
* coloring the entire footer blue to make it more unified
* moving the attribution note to the bottom and leading with the logo bar, to make it clearer that you are getting information about who is publishing the site. 
* Adding a "Get PRA help" link 
* Moving the links from the logo bar into the sub footer. I also switched them from horizontal stacking to vertical since we're adding another link. If more are added, I would recommend adding labels to make them easier to scan. 

cc @nfraseromb @qhirschomb @qmanderson1 who noted these issues from usability testing

**Comment by hursey013** [comment]
Updated footer: https://github.com/GSA/digitalgov-pra/commit/4d067ac83efe4be782fb00b754af99d2dd413640

Preview link: https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/

**Comment by qhirschomb** [comment]
I love how this looks! Any thoughts from others?

**Comment by nfraseromb** [comment]
Yeah same.   Not sure if Quinn and Michael can see the images since I couldn’t download, but here is the link for them in case not:  https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/

**Comment by hursey013** [comment]
Going to go ahead and close this one, and can tackle any other follow up with the footer in new issues.
