### ISSUE TITLE
Glossary entry copy: PRA

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#174]
On the [About the PRA page](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/about/), there is a Glossary icon on the first sentence:

> The Paperwork Reduction Act (PRA) is **a law governing how federal agencies collect information from the American public**. 

When you click on the Glossary icon, the entry says the same exact thing; 

> A law governing how federal agencies collect information from the American public.

Which doesn’t tell the user anything new (why have it?). Can you expand upon it in the Glossary entry? Should users know that you are referring to the 1995 one (and link to it?), and not the initial one from 1980?

**Comment by amandacostello** [comment]
This is in the glossary as (almost) the same content to provide a PRA definition for folks who don't enter the site from the homepage or go through the about page. Also, current PRA policy involves both the 1980 law and the 1995 amendment.
