### ISSUE TITLE
Glossary entry copy: OMB

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#175]
On the [About the PRA page](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/about/), there is a Glossary icon on OMB:

> The Office of Information and Regulatory Affairs (OIRA), under the **Office of Management and Budget** (OMB).. 

When you click on the Glossary icon, the entry says the same exact thing; 

> Office of Management and Budget

Which doesn’t tell the user anything new (why have it?). Can you expand upon it in the Glossary entry? Maybe explain what the OMB does, which Office it’s under @ WH, etc.?

**Comment by amandacostello** [comment]
Added content that it's under the executive office of the president
