### ISSUE TITLE
Content inconsistency; suggested correction

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#177]
On the [Do I need clearance?](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/do-i-need-clearance/) page: 

> Who are you collecting information from?
> Members of the public
> Generally, this means people or groups outside of the federal government. Some groups that are considered members of the public include:
> 
> - Individual people (including federal contractors)
> - Businesses and associations
> - **State, tribal, and local governments**
> - Foreign governments, businesses, and individual people

The glossary definition for person ends with, “Also includes state, territorial, tribal, or local governments.” 
 ~ should _**territorial**_ be added in the third bullet for consistency? 
If so, use the same order.

**Comment by amandacostello** [comment]
Fixed!
