### ISSUE TITLE
Glossary text: person (suggested copy edit, and typo)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#178]
Not sure if this needs any kind of approval higher up, but, on the [Do I need clearance?](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/do-i-need-clearance/) page, there is a Glossary icon on the word, _person_: 

> Direct observation, such as watching how long it takes a **person** to complete a transaction, or how someone uses a new website to find answers.

Here, the Glossary definition of a _person_ states: 

> An individual, partnership, association, corporation, legal representative, or a group of these. Also includes State, territorial, tribal, or local governments.

However, referring to a corporation or other non-human entities as a person could be seen as political/partisan. To remain neutral, perhaps use: 

> For purposes regarding the Paperwork Reduction Act, a “person” can be an individual, individuals representing a partnership, association, corporation, legal representative—or any combination of these. Also includes state, territorial, tribal, or local governments.

_** this also corrects the typo where the word _state_ is mistakenly capitalized in the current entry's second sentence._

**Comment by amandacostello** [comment]
Replaced "a person" with "someone" to avoid triggering the glossary link, and updated the glossary definition.
