### ISSUE TITLE
Unclear copy: page and glossary entry

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#179]
On the [Converting forms from paper to digital](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/do-i-need-clearance/form-updates-and-conversions/) page, it has a Glossary icon on "non-substantive change." The page copy has: 

> As long as the approved form fields and questions are not changed and the digital materials collects the same information, OIRA would likely consider conversion to an electronic format a **non-substantive change** to an already approved collection, and it **wouldn’t need additional approval**.

However, when you click the Glossary icon for _non-substantive change_, the entry says it _does_ require approval: 

> A change made to an information collection that **requires OIRA review and approval** but does not require public comment.

Some may get confused as to why the page copy references an already-approved collection (wouldn't need additional approval), but the glossary entry does not (requires approval).

**Comment by amandacostello** [comment]
Updated text in 1st paragraph on page to "wouldn't need additional public comment."
