### ISSUE TITLE
Is link correct?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#180]
On the [PRA and the Web](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/do-i-need-clearance/pra-and-the-internet/) page:  

> Some social media and web-based technologies are not subject to the PRA, and don’t need approval; broader clarifications are in the [Social Media Guidance Memo](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/assets/inforeg/SocialMediaGuidance_04072010.pdf).

This April 7, 2010 memo -- is it still in use? I searched the code on the [OMB Memos](https://www.whitehouse.gov/omb/information-for-agencies/memoranda/) page and the pdf file for Social Media Guidance Memo is not listed.

**Comment by amandacostello** [comment]
Yes, this memo is still active policy from OMB, approved by general counsel.
