### ISSUE TITLE
Fix numerals

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#185]
On the [PRA approval process](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/clearance-process/) page: 

Always spell out zero through nine; use numerals for 10 and above: 

1) “While the PRA approval process takes at least 90 days, you don’t have to extend your project timeline by **3 months**.” 

change to: `three months`

2) “Most agencies estimate **6 to 9 months** for PRA clearance from start to finish. By law, this process includes at least **3 months** of public comment.” 

Change to: `six to nine months` and `three months`

**Comment by amandacostello** [comment]
Fixed!
