### ISSUE TITLE
Is a Glossary entry missing?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#186]
On the [PRA approval process](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/clearance-process/) page:  

> With your agency, you’ll submit an Information Clearance Request (ICR) for review.

ICR is the first initialism I’ve seen without a Glossary icon and link. Will one be added?
One exists for _information clearance_, but it is not clear if _Information Clearance Request_ is a form to fill out, or just a process.

**Comment by amandacostello** [comment]
Putting in a new definition for ICR, but forwarding to OIRA and OMBGC for approval and clearance.

> *Information Collection Request (ICR):* Details about a proposed collection, reviewed by the agency, public, and OIRA desk officers.

**Comment by amandacostello** [comment]
@qhirschomb @mmcmanusOMB: could you take a look at this new glossary entry, let me know what you think and if it needs OGC's eyes.
