### ISSUE TITLE
Glossary entry copy: ROCIS

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#187]
On the [PRA approval process](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/clearance-process/) page: 

> ICR’s are submitted to OMB through a system called ROCIS.

There is a Glossary icon on ROCIS, which says: 

> The digital platform used by agencies to submit PRA clearance requests to OIRA.

but, the acronym isn’t explained (as is everywhere else). 
I found this in [a GSA pdf about ROCIS](https://www.gsa.gov/cdnstatic/ROCIS_PIA%20May%202018.pdf): 

> Regulatory Information Service Center (RISC) RISC/OIRA Combined Information System (ROCIS)

Perhaps update this Glossary entry to be: 

> Regulatory Information Service Center (RISC) RISC/OIRA Combined Information System (ROCIS) is the digital platform used by agencies to submit PRA clearance requests to OIRA.

**Comment by amandacostello** [comment]
Fixed!
