### ISSUE TITLE
Page copy edit suggestion

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#188]
On the [Types of PRA clearance](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/clearance-types/) page: 

> Generic clearances almost always involve statistical methods and analysis and most information collections are not appropriate for generic clearances.

Perhaps use: 

> Generic clearances almost always involve statistical methods and analysis—however, most information collections are not appropriate for generic clearances.

**Comment by amandacostello** [comment]
Clarified!
