### ISSUE TITLE
Page copy edit suggestion

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#189]
On the [Types of PRA clearance](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/clearance-types/) page: 

> If you feel a generic might be suitable for your needs you should work with your agency’s PRA office who will work with OIRA to map out details of what information can and can’t be used under the generic clearance. 

A bit long for one sentence ~ perhaps use: 

> If you feel a generic might be suitable for your needs, you should work with your agency’s PRA office. They will work with OIRA to map out details of what information can and can’t be used under the generic clearance.

**Comment by amandacostello** [comment]
Fixed!
