### ISSUE TITLE
Glossary edit needed: Federal Register

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#193]
The Glossary entry for **Federal Register**: 

> The daily journal of the United States **Government**. Its use is required by the PRA to gather comments from the public during the **60** and **30** day comment periods.  

1) It is incorrect to capitalize nouns like government, federal, or agency -- unless the word is part of a proper noun (i.e., Federal Acquisition Service, Army Ballistic Missile Agency). 
Use a lowercase _g_ for United States government.

2) Hyphens are needed for time periods; change end to: "60- and 30-day comment periods."

**Comment by amandacostello** [comment]
Fixed!
