### ISSUE TITLE
Glossary edit needed: capital cost

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#194]
The entry for **capital cost** says: 

> One-time expenses, buying something needed to answer the information collection request.

but _capital cost_, _one-time_, and _something_ are all singular -- _expenses_ (plural) doesn't fit/sound right. Change to: 

> A one-time expense to buy something that is needed to answer the information collection request.

**Comment by amandacostello** [comment]
Fixed!
