### ISSUE TITLE
Glossary edit needed: PII

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#207]
The Glossary entry just repeats the term, so, it should be expanded for clarity--

It would be helpful for users if it included some examples of PII (name, social security number, etc.), or the full definition ~ 

GSA defines PII at https://insite.gsa.gov/pii as: 

> Personally identifiable information (PII) can be used to distinguish or trace an individual’s identity, either alone or when combined with other information that is linked or linkable to a specific individual. Per OMB Circular A-130.

Also, from the [GSA Rules of Behavior for Handling Personally Identifiable Information (PII)](https://insite.gsa.gov/cdnstatic/CIO_P2180.1_GSA_Rules_of_Behavior_for_Handling_Personally_Identifiable_Information_%28PII%29_%28Signed_on_October_29__2014%29.pdf) PDF: 

> Personally Identifiable Information (PII) – information about a person that contains some unique identifier, including but not limited to name or Social Security Number, from which the identity of the person can be determined. OMB Memorandum M-10-23 (June 25, 2010), updated the term “PII”: “The definition of PII is not anchored to any single category of information or technology. Rather, it requires a case-by-case assessment of the specific risk that an individual can be identified. In performing this assessment, it is important for an agency to recognize that non-PII can become PII whenever additional information is made publicly available — in any medium and from any source — that, when combined with other available information, could be used to identify an individual.”

**Comment by qhirschomb** [comment]
@mmcmanusOMB do we have something perhaps from privacy branch we could use that is already approved?

**Comment by qhirschomb** [comment]
@ToniBonittoGSA Have been advised by the privacy branch to utilize OMB Circular A-130's definition

**Comment by qhirschomb** [comment]
Appendix II of A-130 discusses a few examples, if that is helpful, but it is supposed to be a broad definition
