### ISSUE TITLE
Copy correction

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov-pra#210]
On the [Supporting Statements](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/clearance-process/supporting-statement/) page: 

> The agency must have a need for the information/data to be collected ... 

Plain Language guidelines suggest that we [refrain from using slashes](https://www.plainlanguage.gov/guidelines/conversational/dont-use-slashes/) as a substitution for words. 

Suggestions: 
 - use just one word; `information`
 - use both, replacing the fwd slash: `information or data`

**Comment by amandacostello** [comment]
Fixed!
