### ISSUE TITLE
Demo: Chief Data Officer

### ISSUE THREAD

**Issue by qhirschomb** [GSA/digitalgov-pra#229]
On https://demo.pra.digital.gov/contact/ under **Help submitting an information request**, we received a suggestion to add the Chief Data Officer to this list:

Office of the General Counsel (OGC)
Chief Information Officer (CIO)
Regulatory Affairs / Regulatory Secretariat

**Comment by mmcmanusOMB** [comment]
I will do this

**Comment by qhirschomb** [comment]
Done
