### ISSUE TITLE
Demo Feedback: FDIC Contact

### ISSUE THREAD

**Issue by qhirschomb** [GSA/digitalgov-pra#230]
We received a note from FDIC with their PRA contact information to add to the drop down menu on https://demo.pra.digital.gov/contact/

At the FDIC PRA requests are handled by PRA Clearance Officers within the Legal Division pursuant to a delegation from the Chief Information Officer to the General Counsel.

Here is how you can contact this office:

Phone:
202-898-3767

Email:
PRA@fdic.gov

**Comment by mmcmanusOMB** [comment]
I will do this.

**Comment by qhirschomb** [comment]
Done
