### ISSUE TITLE
Demo Feedback: External Links - tabs vs page refresh

### ISSUE THREAD

**Issue by qhirschomb** [GSA/digitalgov-pra#231]
We received some interest in having external links open as new tabs instead of going directly to new links. This is something that probably needs user testing to figure out if this is a common concern or an isolated issue

**Comment by mmcmanusOMB** [comment]
Jeremy - is this something digital.gov can code?

**Comment by jeremyzilar** [comment]
@mmcmanusOMB @qhirschomb This is something that not advised to do and there is strong supporting evidence in the field that this is not a great user experience or great for accessibility.

In fact, we (digital.gov) should publish something on this for clarity.

**Comment by qhirschomb** [comment]
@jeremyzilar that makes sense - feel strongly that we should follow best practices. thanks!
