### ISSUE TITLE
Demo Feedback: Supporting Statements A & B

### ISSUE THREAD

**Issue by qhirschomb** [GSA/digitalgov-pra#236]
We received feedback on https://demo.pra.digital.gov/clearance-process/supporting-statement

- Suggest including a link the Supporting Statements Parts A and B, with instructions.

- Also suggested including a discussion pertaining to collections that proposed to use statistical methods and linking the relevant OMB resources.

**Comment by mmcmanusOMB** [comment]
We will be adding supporting statement A list of questions. Supporting Statement B will be reviewed for future action.
