### ISSUE TITLE
Refer to OIRA/OMB consistently throughout the site

### ISSUE THREAD

**Issue by qmanderson1** [GSA/digitalgov-pra#37]
Denote that OIRA and OMB are the same organization or use one or the other consistently throughout the site. Going back and forth between the two was confusing to users during testing.

**Comment by amandacostello** [comment]
This one is kind of weird, because their own guidance flip flops on this a lot! An idea:

- **OMB** issues the approval
- **OIRA** is the office reviewing the request on behalf (or as a part of) OMB.

**Comment by qmanderson1** [comment]
That sounds like a good way to explain it. I'd go with the language "as part of" so folks understand that OIRA is a part of OMB and not a separate entity that's been contracted out by OMB.
