### ISSUE TITLE
Minor: PRA goes lower-case in the glossary

### ISSUE THREAD

**Issue by ecayer** [GSA/digitalgov-pra#49]
If you click on the underlined "PRA," then look in the glossary, the text appears as "pra."  Can it be PRA instead?

**Comment by ecayer** [comment]
Same thing with PII :-)

**Comment by hursey013** [comment]
This is a limitation of the https://github.com/18F/glossary unfortunately - I think it would be best to fix this upstream so closing this out for now.

**Comment by ecayer** [comment]
Could you possibly say a little more about where "upstream" is?

**Comment by hursey013** [comment]
The glossary library was built by 18F, I would suggest opening an issue on the project's repo: https://github.com/18F/glossary
