### ISSUE TITLE
Is the sidenav easy to use and understand?

### ISSUE THREAD

**Issue by cmajel** [GSA/digitalgov-pra#88]
A user should be able to use the sidenav to determine:
* where they are
* what other content exists on the page they are on
* that there are separate, related pages they can navigate to

We have a few visual styles under consideration, and also have some open questions like:
* How should current place be shown? What is most effective?
* Do we need breadcrumbs / a section header?
* Does the "overview" title work when it is different from the title of the page?

**Comment by cmajel** [comment]
An update on this based on current design work discussed with @hursey013 

It feels like the anchor links could become confusing. We suggest we show two options.

* On current site, we show a version with *just* page links, no anchor links. It would look like this:
<img width="301" alt="Screen Shot 2019-04-19 at 4 53 38 PM" src="https://user-images.githubusercontent.com/2374206/56443697-b9641700-62c3-11e9-974b-40d7043ae223.png">

* We consider testing a second version with anchor links, and that could look like this:
<img width="289" alt="Screen Shot 2019-04-19 at 4 53 22 PM" src="https://user-images.githubusercontent.com/2374206/56443690-b406cc80-62c3-11e9-8a99-d68adf1fd173.png">

**Comment by hursey013** [comment]
These changes have been integrated in, closing this.
